udated puppycore_noarch from woofCE

diff --git a/woof-code/rootfs-packages/puppycore_noarch/lib/dhcpcd/dhcpcd-hooks/99-notify b/woof-code/rootfs-packages/puppycore_noarch/lib/dhcpcd/dhcpcd-hooks/99-notify
--- a/woof-code/rootfs-packages/puppycore_noarch/lib/dhcpcd/dhcpcd-hooks/99-notify
+++ b/woof-code/rootfs-packages/puppycore_noarch/lib/dhcpcd/dhcpcd-hooks/99-notify
@@ -1,56 +1,49 @@
 #Notify user of interface state changes
 
-display_notice()
-{
-	export DISPLAY=:0
-	export TEXTDOMAIN=dhcpcd_notify
-	export OUTPUT_CHARSET=UTF-8
-	. gettext.sh
-	case "$reason" in
+case "$reason" in
+	BOUND|REBOOT|STATIC|CARRIER|RELEASE|NOCARRIER|IPV4LL|TIMEOUT|FAIL) ok=1;;
+	*) exit ;;
+esac
+
+[ -f /etc/dhcpcd_state_notify ] || exit
+
+pidof Xorg || pidof X || exit
+
+export DISPLAY=:0
+export TEXTDOMAIN=dhcpcd_notify
+export OUTPUT_CHARSET=UTF-8
+
+case "$reason" in
 	BOUND|REBOOT|STATIC) #up
-		if [ "$(which notify)" == "" ]; then
-		gtkdialog-splash -placement top -timeout 4 -bg green -text "`eval_gettext \"\\\$new_ip_address acquired on \\\$interface\"`"
-		else
-		notify "`eval_gettext \"\\\$new_ip_address acquired on \\\$interface\"`"
-		fi
+		PLACEMENT="bottom"
+		BG="green"
+		MSG="$(printf "$(gettext '%s acquired on %s')" "$new_ip_address" "$interface")"
 		;;
 	CARRIER) #ifup
 		ssid="$(wpa_cli -i $interface status 2>/dev/null | grep ^ssid | cut -f 2 -d =)"
-		
-		if [ "$(which notify)" == "" ]; then
-		gtkdialog-splash -placement top -timeout 4 -bg orange -text "`eval_gettext \"Requesting IP address for \\\$interface \\\$ssid\"`" &
-		else
-		notify "`eval_gettext \"Requesting IP address for \\\$interface \\\$ssid\"`"
-		fi
-		
-		 ;;
+		PLACEMENT="bottom-left"
+		BG="orange"
+		MSG="$(printf "$(gettext 'Requesting IP address for %s %s')" "$interface" "$ssid")"
+		;;
 	RELEASE) #release
-		if [ "$(which notify)" == "" ]; then
-		gtkdialog-splash -placement top -timeout 4 -bg orange -text "`eval_gettext \"Releasing \\\$interface\"`" 
-		else
-		notify "`eval_gettext \"Releasing \\\$interface\"`"
-		fi
+		PLACEMENT=bottom
+		BG=orange
+		MSG="$(printf "$(gettext 'Releasing %s')" "$interface")"
 		;;
 	NOCARRIER) #down
-		
-		if [ "$(which notify)" == "" ]; then
-		gtkdialog-splash -placement top -timeout 4 -bg hotpink -text "`eval_gettext \"\\\$interface is down\"`"
-		else
-		notify "`eval_gettext \"\\\$interface is down\"`"
-		fi
+		PLACEMENT="bottom"
+		BG="hotpink"
+		MSG="$(printf "$(gettext '%s is down')" "$interface")"
 		;;
 	IPV4LL|TIMEOUT|FAIL) #timeout
-		if [ "$(which notify)" == "" ]; then
-		gtkdialog-splash -placement top -timeout 4 -bg red -text "`eval_gettext \"IP address request failed on \\\$interface\"`"
-		else
-		notify "`eval_gettext \"IP address request failed on \\\$interface\"`"
-		fi
-		 ;;
-	esac
-}
+		PLACEMENT="bottom"
+		BG="red"
+		MSG="$(printf "$(gettext 'IP address request failed on %s')" "$interface")"
+		;;
+esac
 
-
-if echo "$reason" | grep -q -E 'BOUND|REBOOT|STATIC|CARRIER|RELEASE|NOCARRIER|IPV4LL|TIMEOUT|FAIL';then
-	[ -f /etc/dhcpcd_state_notify ] && display_notice
+if [ "$MSG" ] ; then
+	gtkdialog-splash -placement $PLACEMENT -timeout 4 -bg $BG -text "$MSG"
 fi
 
+### END ###
diff --git a/woof-code/rootfs-packages/puppycore_noarch/usr/bin/uefi-usb-installer b/woof-code/rootfs-packages/puppycore_noarch/usr/bin/uefi-usb-installer
--- a/woof-code/rootfs-packages/puppycore_noarch/usr/bin/uefi-usb-installer
+++ b/woof-code/rootfs-packages/puppycore_noarch/usr/bin/uefi-usb-installer
@@ -33,9 +33,7 @@
 # +gettext
 # +grubx*.efi.tar.xz from jamesbond
 #-----------------------------------------------------------------------------#
-ver=0.2
-
-[ "`whoami`" != "root" ] && exec sudo -A ${0} ${@} #110505
+ver=0.5
 
 # vars
 . /etc/DISTRO_SPECS
@@ -48,20 +46,72 @@ ABTMSG=$(gettext "You aborted the installation.")
 FULLINST=yes
 MNTERR=$(gettext "Aborting... Failed to mount ")
 CPERR=$(gettext "Copy error")
-SYSDIR=`find /usr -type d -name 'syslinux' -maxdepth 4`
-LABEL=""
-DISTRO=""
-VERSION=""
-INITRDXZ=""
+BOOTLABEL='puppy'
 
 # functions====================================================================
+
+# $1: drive
+write_wee_mbr() {
+	XDEV=${1##*/}
+	BLOCKDEV=$1
+	WEE_MBR='/usr/share/g4dos/wee.mbr'
+	if [ ! -f $WEE_MBR ] ; then
+		echo "file not found: $WEE_MBR"
+		exit 1
+	fi
+	cp ${WEE_MBR} /tmp/wee.mbr
+	## Read disk signature and partition table from MBR
+	## and write it to wee.mbr:
+	dd if=${BLOCKDEV} bs=1 skip=439 count=72 2>/dev/null | \
+		dd of=/tmp/wee.mbr bs=1 seek=439 conv=notrunc
+	## backup MBR
+	dd if=${BLOCKDEV} of=/tmp/${XDEV}.mbr bs=512 count=63
+	## Write wee MBR to $MBR_DEV
+	echo "Installing bootloader(Wee) on ${BLOCKDEV} ..."
+	dd if=/tmp/wee.mbr of=${BLOCKDEV}
+}
+
+# $1: directory
+# $2: distro
+# $3: pmedia
+copy_g4dos_cd() {
+	if [ ! -d "$1" ] ; then
+		return 1
+	fi
+	cp -fv /usr/share/g4dos/pcd/* "$1"/
+	if [ "$2" ] ; then #distro
+		if [ "$2" = "auto" ] ; then
+			. /etc/DISTRO_SPECS
+			sed -i "s%#distrodesc#%${DISTRO_NAME} ${DISTRO_VERSION}%" "$1"/menu.lst
+		else
+			sed -i "s%#distrodesc#%${2}%" "$1"/menu.lst
+		fi
+	fi
+	if [ "$3" ] ; then #pmedia
+		sed -i "s|pmedia=cd|pmedia=${3}|" "$1"/menu.lst
+	fi
+	if [ -f /usr/lib/grub4dos/grldr ] ; then
+		cp /usr/lib/grub4dos/grldr "$1"/
+	elif [ -f /usr/share/g4dos/grldr ] ; then
+		cp /usr/share/g4dos/grldr "$1"/
+	fi
+}
+
 error_func() {
 	#rm -r "$TMP"
 	retval="$3"
 	color="$2"
 	[ "$retval" ] || color=red retval=$2
-	/usr/lib/gtkdialog/box_ok "Error!" error "$1"
+	gtkdialog-splash -close box -bg $color -text "$1"
 	[ "$retval" ] && exit "$retval" || exit 1
+}
+
+copy_boot_menu() {
+	sed -e "s/DISTRO_FILE_PREFIX/${DISTRO_FILE_PREFIX}/g" \
+		-e "s/DISTRO_DESC/${DISTRO_FILE_PREFIX} ${DISTRO_VERSION}/g" \
+		-e "s/#distrodesc#/${DISTRO_FILE_PREFIX} ${DISTRO_VERSION}/g" \
+		-e "s/BOOTLABEL/${BOOTLABEL}/g"  \
+		-e 's/pmedia=cd/pmedia=usbflash/' ${1} > ${2}
 }
 
 # check running state, frugal and live only supported
@@ -75,7 +125,7 @@ pupcheck() {
 # check Grub UEFI
 grub2_chk() {
 	GRUB_ERR="No suitable grub2 file found. Exiting"
-	ls /usr/share/grub2-efi | grep -qE 'grubx[0-9][0-9].efi.tar.xz' || error_func "$GRUB_ERR" orange $?
+	ls /usr/share/grub2-efi | grep -qE 'grub.*.efi.*' || error_func "$GRUB_ERR" orange $?
 }
 
 # find usb drive
@@ -88,37 +138,25 @@ $(gettext "A USB drive can not be found. Is it plugged in? Exiting now")
 	fi
 }
 
-# fix mbr
-mbr_func () {
-	device="$1"
+# sets $USBDRV and $dev1
+func_choose_drv() {
 	echo "======================"
-	echo "mbr_func"
-	echo "======================"
-	dd if=${device} of=/tmp/mbr_old.bin bs=446 count=1
-	
-	dd if=${SYSDIR}/mbr.bin of=${device} bs=440 count=1 conv=notrunc
-	retval="$?"
-	return $retval
-}
-
-# gui 1
-func_gui1() {
-	echo "======================"
-	echo "func_gui1"
+	echo "func_choose_drv"
 	echo "======================"
 	
 	# construct gui 1
 	DESC=$(gettext "USB device - ")
 	while read line
-	do dev="${line%%|*}"
-	desc="${line##*|}"
-	echo "<radiobutton>
+	do
+		dev="${line%%|*}"
+		desc="${line##*|}"
+		echo "<radiobutton>
 	 <label>$DESC $dev $desc</label>
 	 <variable>$dev</variable>
 	</radiobutton>" >> $TMP/uefi-wiz-radbtn
 	done <"$TMP"/uefi-wiz-list
 	RADBTN=`cat $TMP/uefi-wiz-radbtn`
-	export gui1='<window title="UEFI usb installer - 1 v-'$ver'" resizable="false">
+	export gui1='<window title="UEFI usb installer - 1 v-'$ver'" window-position="1">
 	<vbox space-expand="true" space-fill="true">
 	  <text use-markup="true"><label>"<b>'$(gettext "Welcome to the UEFI usb drive installer wizard.")'</b>"</label></text>
 	  <hseparator></hseparator>
@@ -130,35 +168,33 @@ func_gui1() {
 	</vbox>
 	</window>'
 	gtkdialog -p gui1 > "$TMP"/uefi-chosen
-	CHOSEN=`grep "true" "$TMP"/uefi-chosen|cut -d '=' -f1`
-	echo $CHOSEN
-	if [ ! "$CHOSEN" ];then 
-	error_func "$ABTMSG" yellow 0
+	USBDRV=`grep "true" "$TMP"/uefi-chosen|cut -d '=' -f1`
+	echo $USBDRV
+	if [ ! "$USBDRV" ];then 
+		error_func "$ABTMSG" yellow 0
 	fi
-	DESC2=`grep "$CHOSEN" "$TMP"/uefi-wiz-list|rev|cut -d '|' -f1|rev` 
+	dev1=${USBDRV}1
+}
+
+
+func_gui1() {
+	DESC2=`grep "$USBDRV" "$TMP"/uefi-wiz-list|rev|cut -d '|' -f1|rev` 
 	# splash some info
 	DMSG1=$(gettext "You have chosen ")
 	DMSG2=$(gettext "When you click OK gparted will open to allow you to partition your \
 	drive. You must make a FAT32 type partition. Be sure the drive is not mounted and be aware that all data on \
 	the drive will be destroyed. You may want to write this down.")
 	DMSG3=$(gettext "Be sure to mark the partition with the boot flag in gparted")
-	export guigp='<window title="UEFI usb installer v-'$ver'" resizable="false">
-	<vbox space-expand="true" space-fill="true">
-	  <frame>
-		<text><label>"'"$DMSG1 $CHOSEN - $DESC2"'"</label></text>
-		<text><label>"'"$DMSG2"'"</label></text>
-		<text use-markup="true"><label>"<b>'"$DMSG3"'</b>"</label></text>
-	  </frame>
-	<hbox homogeneous="true"><button ok></button></hbox>
-	</vbox>
-	</window>'
-	eval `gtkdialog -p guigp -c`
-	[ "$EXIT" = "abort" ] && error_func "$ABTMSG" yellow 0
+	/usr/lib/gtkdialog/box_yesno --info --ok-cancel  "UEFI usb installer v-${ver}" \
+		"$DMSG1" "$USBDRV - $DESC2" "$DMSG2" "<b>$DMSG3</b>"
+	if [ $? -ne 0 ] ; then
+		error_func "$ABTMSG" yellow 0
+	fi
 	# run gparted on chosen partition
 	GPERR=$(gettext "Gparted exited with an error. Exiting.")
-	gparted "$CHOSEN"
+	gparted "$USBDRV"
 	[ "$?" = 0 ] || error_func "$GPERR" $?
-	dev1=${CHOSEN}1
+
 	sync
 	# check fs type
 	FSNOT=$(gettext " is the wrong filesystem for that partition!")
@@ -169,24 +205,19 @@ func_gui1() {
 	mount|grep -q "$TMPMNT1" || mount -t vfat "$dev1" "$TMPMNT1" -o utf8
 	CSIZE=`df -m "$dev1"|awk '{print $2}'|tail -n1`
 	if [ "$CSIZE" -lt 20 ];then
-	SIZERR=$(gettext "Your boot partition is too small. Try again")
-	umount "$TMPMNT1"
-	error_func "$SIZERR" 77
+		SIZERR=$(gettext "Your boot partition is too small. Try again")
+		umount "$TMPMNT1"
+		error_func "$SIZERR" 77
 	fi
 	umount "$TMPMNT1"
 	
 	# check if boot flag set
 	NOTBOOT=$(gettext " device is not bootable! Try again.")
-	disktype "${CHOSEN}"|grep -q 'bootable'
-	[ "$?" -ne 0 ] && error_func "$CHOSEN $NOTBOOT" 78
-	
-	# make bootable
-	MBRF=(gettext "Failed to make bootable.")
-	mbr_func "$CHOSEN"
-	[ "$?" -ne 0 ] && error_func "$MBRF" "$?"
-	
+	disktype "${USBDRV}"|grep -q 'bootable'
+	[ "$?" -ne 0 ] && error_func "$USBDRV $NOTBOOT" 78
+
 	FPART1=`probepart|grep -iE 'fat'|cut -d '|' -f1`
-	
+
 	rm -rf $TMP/UEFI* 2>/dev/null
 	# sanity check
 	FST1=`guess_fstype "$dev1"`
@@ -194,13 +225,11 @@ func_gui1() {
 	MSG_FS1_1=$(gettext "is of type")
 	MSG_FS1_2=$(gettext "it needs to be vfat. Exiting now.")
 	if ! [ "`echo $FST1|grep -i 'fat'`" ];then
-	error_func "$dev1 $MSG_FS1_1 $FST1 ${MSG_FS1_2}" 4
+		error_func "$dev1 $MSG_FS1_1 $FST1 ${MSG_FS1_2}" 4
 	fi
-	
 	sync
-	
-	func_frugal "$dev1"
 }
+
 
 # find and copy pup files
 copy_func(){
@@ -211,36 +240,19 @@ copy_func(){
 	# puppy_*_*.sfs, z(a,y)drv_*_*.sfs to the vfat partition
 	SRCF="$1" dev1="$2"
 	PUPPY=`ls "$SRCF"|grep '^puppy_'|grep 'sfs$'`
-	DISTRO=`echo "$PUPPY"|cut -d _ -f2`
-	VERSION=`echo "$PUPPY"|cut -d _ -f3`
-	VERSION=${VERSION%.*}
-	LABEL="$DISTRO $VERSION"
-	echo "$LABEL"
+	DISTRO_FILE_PREFIX=`echo "$PUPPY"|cut -d _ -f2`
+	DISTRO_VERSION=`echo "$PUPPY"|cut -d _ -f3`
+	DISTRO_VERSION=${DISTRO_VERSION%.*}
+	echo "$DISTRO_FILE_PREFIX $DISTRO_VERSION"
 	mount|grep -q "$TMPMNT1" || mount -t vfat "$dev1" "$TMPMNT1" -o utf8
 	[ "$?" = 0 ] || error_func "$MNTERR ${dev1}" $?
 	
 	# Only support root of drive for now.. 
 	HOMEDIR="$TMPMNT1"
 	# copy *sfs
-	for s in `ls $SRCF|grep 'sfs$'`;do
-	  cp -a "${SRCF}"/"$s" $HOMEDIR
+	for s in `ls $SRCF|grep 'sfs$'` vmlinuz initrd.gz ;do
+		cp -a "${SRCF}"/"$s" $HOMEDIR
 	done
-	sync
-	# copy kernel and initramfs
-	#for v in vmlinuz initrd.gz initrd.xz; do
-	
-	if [ -f "${SRCF}"/initrd.xz ]; then
-	INITRDXZ="yes"
-	cp -a "${SRCF}"/initrd.xz $HOMEDIR
-	elif [ -f "${SRCF}"/initrd.gz ]; then
-	INITRDXZ="no"
-	cp -a "${SRCF}"/initrd.gz $HOMEDIR
-	fi
-	
-	cp -a "${SRCF}"/vmlinuz $HOMEDIR
-	
-	#done
-	touch $HOMEDIR/USBFLASH # maybe not needed with new init?
 	sync
 	PID=`cat /tmp/u_pid`
 	kill -9 $PID
@@ -259,7 +271,7 @@ func_frugal() {
 	FMSG1=$(gettext "Now it's time to specify your files.")
 	FMSG2=$(gettext "Please choose where the Puppy files are located. \
 The Puppy <u>must</u> be UEFI compatible!!!")
-	export gui2='<window title="UEFI usb installer - frugal v-'$ver'" resizable="false">
+	export gui2='<window title="UEFI usb installer - frugal v-'$ver'" window-position="1">
 	  <vbox>
 	    <text use-markup="true"><label>"<b>'$FMSG1'</b>"</label></text>
 	    <hseparator></hseparator>
@@ -281,7 +293,7 @@ The Puppy <u>must</u> be UEFI compatible!!!")
 	CPMSG2="$(gettext ". Please wait...")"
 	case "$EXIT" in 
 	OK)if [ "$rb0" = "true" ];then
-		 gtkdialog-splash -bg yellow -close never -text "$CPMSG1 $dev1 $CPMSG2" &
+		 gtkdialog-splash -bg yellow -close box -text "$CPMSG1 $dev1 $CPMSG2" &
 		 CDPID=$!
 		 echo $CDPID > /tmp/u_pid
 		 mkdir -p /mnt/isomnt #mountpoint
@@ -311,7 +323,7 @@ that you want to use for your install.")" \
 	       ISOMSG=$(gettext "is not an ISO image! Exiting")
 	       error_func "$ISO $ISOMSG" 253
 	     fi
-		 gtkdialog-splash -bg yellow -close never -text "$CPMSG1 $dev1 $CPMSG2" &
+		 gtkdialog-splash -bg yellow -close box -text "$CPMSG1 $dev1 $CPMSG2" &
 		 ISOPID=$!
 		 echo $ISOPID > /tmp/u_pid
 		 mkdir -p /mnt/isomnt #mountpoint
@@ -339,7 +351,7 @@ sfs files,\nTHEN HIGHLIGHT ANY ONE OF THEM in the right pane \nand click the OK 
 	     -stdout --no-buttons --no-cancel --fselect "*" 0 0`"
 	     [ ! $? -eq 0 ] && exit
 	     SRCPATH="${SRCFPATH%/*}"
-	     if [ ! -f "${SRCPATH}"/initrd.gz ] && [ ! -f "${SRCPATH}"/initrd.xz ];then
+	     if [ ! -f "${SRCPATH}"/initrd.gz ];then
 	       FAIL0MSG="$(gettext "No Puppy files found in that directory! Exiting")"
 	       error_func "$FAIL0MSG" 250
 	     fi
@@ -367,95 +379,6 @@ sfs files,\nTHEN HIGHLIGHT ANY ONE OF THEM in the right pane \nand click the OK 
 	esac
 }
 
-# make syslinux bootable
-sys_func () {
-		echo "======================"
-	echo "sys_func"
-	echo "======================"
-	dev1="$1" pic="$2"
-	SYSPLASH=$(gettext "Now installing syslinux in to ")
-	gtkdialog-splash -close never -timeout 3 -bg green -text "$SYSPLASH $dev1" &
-	extlinux -i "$TMPMNT1"
-	for b in vesamenu.c32 chain.c32;do 
-	   cp ${SYSDIR}/$b "$TMPMNT1" 2>/dev/null #top level
-	done
-	sync
-
-# build syslinux.conf	
-cat > "$TMPMNT1"/syslinux.cfg <<SYS
-#display help/boot.msg
-default $DISTRO_FILE_PREFIX
-prompt 1
-timeout 100
-
-
-ui vesamenu.c32
-menu resolution 800 600
-menu title $DISTRO_FILE_PREFIX Live
-menu background ${pic}.png
-menu tabmsg Press Tab to edit entry, Esc for boot prompt
-menu color border 37;40  #80ffffff #00000000 std
-menu color sel 7;37;40 #80ffffff #20ff8000 all
-menu margin 1
-menu rows 20
-menu tabmsgrow 26
-menu cmdlinerow -2
-menu passwordrow 19
-menu timeoutrow 28
-menu helpmsgrow 30
-
-
-
-label ${DISTRO_FILE_PREFIX}
-linux vmlinuz
-initrd initrd.gz
-append pmedia=usbflash
-menu label ${DISTRO_FILE_PREFIX}
-text help
-Start ${DISTRO_FILE_PREFIX} normally.
-endtext
-
-
-label ${DISTRO_FILE_PREFIX}-ram
-linux vmlinuz
-initrd initrd.gz
-append pfix=ram pmedia=usbflash
-menu label $DISTRO_FILE_PREFIX with no savefile
-text help
-Start ${DISTRO_FILE_PREFIX} with no savefile RAM only.
-endtext
-
-
-label ${DISTRO_FILE_PREFIX}-nox
-linux vmlinuz
-initrd initrd.gz
-append pfix=nox pmedia=usbflash
-menu label ${DISTRO_FILE_PREFIX} without graphical desktop
-text help
-Start ${DISTRO_FILE_PREFIX} in command-line mode (Linux console). 
-Graphical desktop later can be started by typing "xwin".
-endtext
-
-
-menu separator
-
-label ${DISTRO_FILE_PREFIX}-nokms
-linux vmlinuz
-initrd initrd.gz
-append pfix=ram,nox pmedia=usbflash
-menu label For machines with severe video problems
-text help
-Start ${DISTRO_FILE_PREFIX} without savefile, without KMS, and run xorgwizard 
-to choose video resolutions before starting graphical desktop.
-endtext
-SYS
-
-if [ "$INITRDXZ"=="yes" ]; then
-sed -i -e "s#initrd.gz#initrd.xz#g" "$TMPMNT1"/syslinux.cfg
-fi
-
-}
-
 # grub2 - make bootable
 boot_func() {
 	echo "======================"
@@ -466,92 +389,65 @@ boot_func() {
 	GSPLASH=$(gettext "Now installing grub2 in to ")
 	gtkdialog-splash -close never -timeout 3 -bg green -text "$GSPLASH $dev1" &
 	GRUBDIR="/usr/share/grub2-efi"
-	GRUB2="$GRUBDIR/grubx64.efi.tar.xz"
 	mkdir -p ${HOMEDIR}/EFI/boot
-	tar -xJvf $GRUB2 -C ${HOMEDIR}/EFI/boot/
-	mv ${HOMEDIR}/EFI/boot/grubx64.efi ${HOMEDIR}/EFI/boot/bootx64.efi
-	mv ${HOMEDIR}/EFI/boot/grubia32.efi ${HOMEDIR}/EFI/boot/bootia32.efi
+
+	if [ -f ${GRUBDIR}/grubia32.efi ] ; then
+		cp ${GRUBDIR}/grubia32.efi ${HOMEDIR}/EFI/boot/bootia32.efi
+	fi
+	if [ -f ${GRUBDIR}/grubx64.efi ] ; then
+		cp ${GRUBDIR}/grubx64.efi ${HOMEDIR}/EFI/boot/bootx64.efi
+	elif [ -f $GRUBDIR/grubx64.efi.tar.xz ] ; then # old stuff
+		tar -xJvf $GRUBDIR/grubx64.efi.tar.xz -C ${HOMEDIR}/EFI/boot/
+		mv ${HOMEDIR}/EFI/boot/grubx64.efi ${HOMEDIR}/EFI/boot/bootx64.efi
+	fi
 	sync
-	
-# add boot image (png)
+
+	# add boot image (png)
 	pic=puppy
 	case ${DISTRO_FILE_PREFIX} in
 		[Tt]ahr*)pic=tahr;;
 		[Ss]lacko*)pic=slacko;;
 		[Xx]enial*)pic=xenial;;
 	esac
-	cp -a ${GRUBDIR}/${pic}.png ${HOMEDIR}/ 2>/dev/null
+	cp -a /usr/share/boot-dialog/${pic}.png ${HOMEDIR}/splash.png 2>/dev/null
 
-# build grub.cfg	
-cat > ${HOMEDIR}/grub.cfg <<GRUB
-insmod png
-background_image /${pic}.png
-set timeout=10
-menuentry "Start $DISTRO_FILE_PREFIX" {
-    linux /vmlinuz pmedia=usbflash
-    initrd /initrd.gz
-}
-menuentry "Start $DISTRO_FILE_PREFIX - RAM only" {
-    linux /vmlinuz pfix=ram pmedia=usbflash
-    initrd /initrd.gz
-}
-menuentry "Start $DISTRO_FILE_PREFIX - No X" {
-    linux /vmlinuz pfix=nox pmedia=usbflash
-    initrd /initrd.gz
-}
-menuentry "Start $DISTRO_FILE_PREFIX - check filesystem" {
-    linux /vmlinuz pfix=fsck pmedia=usbflash
-    initrd /initrd.gz
-}
-menuentry "Start $DISTRO_FILE_PREFIX - No KMS" {
-    linux /vmlinuz nomodeset pmedia=usbflash
-    initrd /initrd.gz
-}
-menuentry "Shutdown" {
-	halt
-}
-menuentry "Reboot" {
-	reboot
-}
-GRUB
+	copy_boot_menu /usr/share/boot-dialog/grub.cfg ${HOMEDIR}/grub.cfg
 
-if [ "$INITRDXZ"=="yes" ]; then
-sed -i -e "s#initrd.gz#initrd.xz#g" ${HOMEDIR}/grub.cfg
-fi
-
-if [ ! -d ${HOMEDIR}/boot ]; then
-mkdir ${HOMEDIR}/boot
-fi
-
-if [ ! -d ${HOMEDIR}/boot/grub ]; then
-mkdir ${HOMEDIR}/boot/grub
-fi
-
-cp -f ${HOMEDIR}/grub.cfg ${HOMEDIR}/boot/grub/grub.cfg
-
-	# add syslinux if wanted
 	ALTMSG=$(gettext "Would you like to add legacy BIOS boot capability to your installation?")
 	Xdialog -title "Add Legacy BIOS" --yesno "$ALTMSG" 0 0 0
-	case $? in
-		0)sys_func $dev1 $pic;;
-		*);;
-	esac
-	
+	if [ $? -eq 0 ] ; then
+		write_wee_mbr ${USBDRV}
+		copy_g4dos_cd ${HOMEDIR} auto usbflash
+	fi
 	mount|grep -q "$TMPMNT1" && umount "$TMPMNT1"
-	
 	HAPPY=$(gettext "Everything looks good. Make sure $dev1 is unmounted and remove the media. \
 After first boot you are given the option to make a \
-'save file'. To keep your changes choose this or to boot to RAM every time don't cretate a save file. \
+'save file'. To keep your changes choose this or to boot to RAM every time don't create a save file. \
 If you have Windows, be sure that you boot to Windows and disable hibernation, aka fast boot, aka hybdrid \
 sleep, etc, and configure your UEFI to disable Secure Boot.")
 	error_func "$HAPPY" green 0 #not an error, but a clean get out!
+
 }
 
+#=========================================================================
+#  main 
+#=========================================================================
 
-#main =========================================================================
 pupcheck
 grub2_chk
 find_usb
+
+if [ "$1" -a -b $1 ] ; then
+	echo chosen via command line: $1
+	USBDRV=$1
+	dev1=${USBDRV}1
+else
+	func_choose_drv
+fi
+
 func_gui1
+func_frugal "$dev1"
+
 [ -d "$TMP" ] && rm -r $TMP #cleanup
+
 exit $?
diff --git a/woof-code/rootfs-packages/puppycore_noarch/usr/sbin/gparted_shell b/woof-code/rootfs-packages/puppycore_noarch/usr/sbin/gparted_shell
--- a/woof-code/rootfs-packages/puppycore_noarch/usr/sbin/gparted_shell
+++ b/woof-code/rootfs-packages/puppycore_noarch/usr/sbin/gparted_shell
@@ -1,88 +1,82 @@
-#!/bin/sh
+#!/bin/ash
 #(c) copyright 2008 Barry Kauler
 #2008 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #v411 BK: wrapper for gparted, prevent indefinite scan at startup on some systems.
-#v424 update desktop drive icons. note, this is also done in /usr/sbin/bootflash, puppyinstaller.
-#v424 report that gparted crash with a non-english locale.
 
-#v424 report that gparted crash with a non-english locale. well, maybe just do this...
-export LANG=C
+export TEXTDOMAIN=gparted_shell
+export OUTPUT_CHARSET=UTF-8
+. gettext.sh
 
-echo -n "" > /tmp/gparted_shell_probe
-PROBEDISK="`probedisk2 | grep -v '|optical|'`"
-echo "$PROBEDISK" |
-while read ONEPROBE
-do
- ONEDRIVE="`echo -n "$ONEPROBE" | cut -f 1 -d '|' | cut -f 3 -d '/'`"
- ONECATEG="`echo -n "$ONEPROBE" | cut -f 2 -d '|'`"
- case $ONECATEG in
-  drive) ONECATEG="internal drive";;
-  usbdrv) ONECATEG="USB drive";;
- esac
- ONEDESCR="`echo -n "$ONEPROBE" | cut -f 3 -d '|' | tr '\"' ' '`"
- echo "<radiobutton><label>${ONEDRIVE} ${ONECATEG}. Descr: ${ONEDESCR}</label><variable>RADIO_${ONEDRIVE}</variable></radiobutton>" >> /tmp/gparted_shell_probe
-done
+if ! which gparted ; then
+	echo "ERROR: gparted is missing"
+	exit 1
+fi
 
- echo "<radiobutton><label>ALL DRIVES. Scan all drives at startup</label><variable>RADIO_all</variable></radiobutton>" >> /tmp/gparted_shell_probe
+case $1 in help)
+	/usr/lib/gtkdialog/box_ok "Gparted" info \
+		"`gettext "At startup, Gparted scans for all drives in the computer, and on some computers this can take a very long time.. here you can choose the drive you want to work on."`" "" \
+		"`gettext "<b>WARNING</b>: A PC may have a single VFAT or NTFS partition, with Windows installed, and you might want to decrease the size of that partition so as to be able to create a Linux partition. For Windows XP this is usually ok. However, Vista gets very upset if the partition is resized and may not work properly afterward -- there may be a fix for this, but we don't know what it is."`"
+	exit
+	;;
+esac
+
+#============================================================================
+
+[ -f /usr/share/pixmaps/gparted.xpm ] & gpicon=/usr/share/pixmaps/gparted.xpm
+[ -f /usr/share/pixmaps/gparted.png ] & gpicon=/usr/share/pixmaps/gparted.png
+[ -z $gpicon ] && gpicon=/usr/share/pixmaps/puppy/harddisk_scsi.svg
+
+(
+	probedisk -show-usbflash | grep -v '|optical|' | \
+	while IFS="|" read ONEDRIVE ONECATEG ONEDESCR ZZZ
+	do
+		ONEDRIVE=${ONEDRIVE##*/} #basename ONEDRIVE
+		case $ONECATEG in
+			drive)    ONECATEG="$(gettext 'internal drive')"  ;;
+			usbdrv)   ONECATEG="$(gettext 'USB drive')"       ;;
+			usbflash) ONECATEG="$(gettext 'USB Flash drive')" ;;
+		esac
+		echo "<radiobutton><label>${ONEDRIVE} ${ONECATEG} -- ${ONEDESCR}</label><variable>RADIO_${ONEDRIVE}</variable></radiobutton>"
+	done
+	echo "<radiobutton><label>$(gettext 'ALL DRIVES. Scan all drives at startup')</label><variable>RADIO_all</variable></radiobutton>"
+) > /tmp/gparted_shell_probe
  
 DRVTAGS="`cat /tmp/gparted_shell_probe`"
 
-height2=$(xdpyinfo | awk '/dimensions/{print $2}' | cut -f 2 -d 'x')
-
-if [ $height2 = 480 ]; then
-vbox1="<vbox scrollable=\"true\" height=\"370\" width=\"400\">"
-else
-vbox1="<vbox>"
-fi
-
-export MAIN_DIALOG="
-<window title=\"Gparted\" resizable=\"false\">
- <vbox>
- $vbox1
-  <text><label>Welcome, Gparted is an application to examine and modify partitions in a disk drive. At startup, the default behaviour is for Gparted to scan for all drives in the computer, and on some computers this can take a very long time. Therefore, this dialog window enables you to make a choice of which drive you want to work on (and Gparted will only scan that drive at startup).</label></text>
-  <text><label>WARNING: A PC may have a single VFAT or NTFS partition, with Windows installed, and you might want to decrease the size of that partition so as to be able to create a Linux partition. For Windows XP/98/95 this is usually ok (but be careful not to make it too small, say 5GB for XP). However, Vista gets very upset if the partition is resized and may not work properly afterward (in some cases won't even start) -- there may be a fix for this, but we don't know what it is.</label></text>
-  
-  <vbox scrollable=\"true\" height=\"140\">
-  ${DRVTAGS}
-  </vbox>
-  
-  </vbox>
-  
-  <hbox>
-   <button>
-    <label>OKAY</label>
-    <action type=\"exit\">OKAYBUTTON</action>
-   </button>
-   <button>
-    <label>CANCEL</label>
-    <action type=\"exit\">CANCELBUTTON</action>
-   </button>
-  </hbox>
-
- </vbox>
+WELCOME_MSG=$(/usr/lib/gtkdialog/xml_info fixed $gpicon 30 "$(gettext 'Gparted is an application to examine and modify partitions in a disk drive.')")
+export MAIN_DIALOG='<window title="Gparted" image-name="'${gpicon}'">
+<vbox>
+	'${WELCOME_MSG}'
+	<frame '$(gettext 'Select drive to work on')'>
+		'${DRVTAGS}'
+	</frame>
+	<hbox>
+		<button space-expand="false" space-fill="false">
+			'"`/usr/lib/gtkdialog/xml_button-icon help`"'
+			<label>"'$(gettext 'Help')'"</label>
+			<action>'${0}' help</action>
+		</button>
+		<button ok></button>
+		<button cancel></button>
+	</hbox>
+</vbox>
 </window>
-"
-
-RETVALS="`gtkdialog3 --program=MAIN_DIALOG`"
-
-[ "`echo "$RETVALS" | grep 'OKAYBUTTON'`" = "" ] && exit
+'
+rm -f /tmp/gparted_shell_probe
+. /usr/lib/gtkdialog/xml_info gtk
+RETVALS="`gtkdialog --center --program=MAIN_DIALOG`"
+eval "$RETVALS"
+[ "$EXIT" != "OK" ] && exit
 
 THEDRIVE="`echo "$RETVALS" | grep '"true"' | cut -f 1 -d '=' | sed -e 's/RADIO_//'`"
 
-[ "$THEDRIVE" = "all" ] && exec gparted
-
-#v424 record state...
-tdPATTERN="/dev/${THEDRIVE}"
-DRVSTATE1="`probepart | grep "$tdPATTERN"`"
+if [ "$THEDRIVE" = "all" ] ; then
+	exec gparted
+fi
 
 gparted /dev/${THEDRIVE}
 
-#v424 update desktop drive icons. note, this is also done in /usr/sbin/bootflash, puppyinstaller...
-#/tmp/pup_event_frontend_block_request is used in /sbin/pup_event_frontend_d to refresh drv...
-DRVSTATE2="`probepart | grep "$tdPATTERN"`"
-if [ "$DRVSTATE1" != "$DRVSTATE2" ];then
- sync
- echo "$THEDRIVE" > /tmp/pup_event_frontend_block_request
-fi
+sync
+echo change > /sys/block/${THEDRIVE}/uevent
 
-###END###
+### END ###
diff --git a/woof-code/rootfs-packages/puppycore_noarch/usr/sbin/icon_switcher b/woof-code/rootfs-packages/puppycore_noarch/usr/sbin/icon_switcher
--- a/woof-code/rootfs-packages/puppycore_noarch/usr/sbin/icon_switcher
+++ b/woof-code/rootfs-packages/puppycore_noarch/usr/sbin/icon_switcher
@@ -1,4 +1,4 @@
-#!/bin/sh -x
+#!/bin/bash
 #(c) Copyright Nov 2007 Barry Kauler www.puppylinux.com
 #2007 Lesser GPL licence v2 (http://www.fsf.org/licensing/licenses/lgpl.html)
 #written dec 2007 for Puppy Linux.
@@ -9,172 +9,207 @@
 #110721 new standardised icons to show when mounted.
 #110912 modify jwm to use menu icon 'start-button.png' if present.
 #120201 rodin.s: internationalized
-#140102 zigbert: gui (gtkdialog) improvements.
-
-mkdir -p /tmp/icon-switcher-proc
 
 export TEXTDOMAIN=icon_switcher
-export TEXTDOMAINDIR=/usr/share/locale
 export OUTPUT_CHARSET=UTF-8
-eval_gettext () {
-  local myMESSAGE=$(gettext "$1")
-  eval echo \"$myMESSAGE\"
-}
-export LANGORG=$LANG
 
-#who called me?
-echo "$0" | grep -q "cli" || GUI=yes
+func_switch (){
 
-#  <text><label>\"${CHARPAD}\"</label></text>
+	echo
+	echo "Setting Desktop Icon Theme..."
 
-ICONSETSGUI=""
-for ONEDIR in `ls /usr/local/lib/X11/themes`
-do
+	NEWTHEME="$1"
+	[ "$NEWTHEME" = "" ] && exit
+	if [ ! -d ${SYSROOT}/usr/local/lib/X11/themes/${NEWTHEME} ] ; then
+		echo "ERROR: ${SYSROOT}/usr/local/lib/X11/themes/${NEWTHEME} does not exist"
+		exit 1
+	fi
+
+	echo "Theme: $NEWTHEME"
+
+
+	#show splash if running in gui mode
+	if [ "$UPDATE" = "true" ]; then
+		/usr/lib/gtkdialog/box_splash -close never -fontsize large -icon_width 60 -icon /usr/share/pixmaps/puppy/puppy_config.svg -text "$(gettext 'Changing theme')" &
+		XPID=$!
+	fi
+	#---
+	for ONESVG in `find ${SYSROOT}/usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -name \*.svg | tr '\n' ' '`; do
+		ONEBASENAME="`basename $ONESVG .svg`"
+		rm -f ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png
+		rsvg-convert -w 48 -h 48 -o ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png $ONESVG
+		rm -f ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}24.png
+	done
+	for ONEPNG in `find ${SYSROOT}/usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -type f -name \*.png | tr '\n' ' '`; do
+		ONEBASENAME="`basename $ONEPNG .png`"
+		cp -f $ONEPNG ${SYSROOT}/usr/local/lib/X11/pixmaps/
+		touch -m ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}.png #v3.98
+	done
+
+	if [ "${SYSROOT}" -a "${NEWTHEME}" != "StandardSvg" ] ; then
+		# fill in the gaps with the StandardSvg icons...
+		for ONESVG in `find ${SYSROOT}/usr/local/lib/X11/themes/StandardSvg/ -maxdepth 1 -name \*.svg | tr '\n' ' '`; do
+			ONEBASENAME="`basename $ONESVG .svg`"
+			if [ -f ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png ] ; then
+				continue
+			fi
+			echo "[StandardSvg] ${ONEBASENAME}.svg -> ${ONEBASENAME}48.png"
+			rsvg-convert -w 48 -h 48 -o ${SYSROOT}/usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png $ONESVG
+		done
+	fi
  
- ONEDIR="/usr/local/lib/X11/themes/$ONEDIR"
+	#new standardised icons to show when mounted...
+	if [ "`which pngoverlay`" -a -e ${SYSROOT}/usr/local/lib/X11/pixmaps/closebox_outline48.png ];then
+		rm -f ${SYSROOT}/usr/local/lib/X11/pixmaps/*_mntd*.png
+		(
+			cd ${SYSROOT}/usr/local/lib/X11/pixmaps
+			cp -fv `which pngoverlay` ./pngoverlay #dumb, but needs to be in same folder.
+			for ONEDRV in card drive floppy optical usbdrv; do
+				./pngoverlay ${ONEDRV}48.png closebox_outline48.png ${ONEDRV}_mntd48.png #background foreground output.
+				./pngoverlay ${ONEDRV}48.png locked_outline48.png ${ONEDRV}_mntd_boot48.png
+			done
+			rm -fv ./pngoverlay
+		)
+	fi
+ 
+	#modify jwm to use menu icon 'start-button.png' if present...
+	#note, similar code also in 3builddistro in Woof.
+	if [ -f ${SYSROOT}/root/.jwmrc-tray ] && [ -f ${SYSROOT}/usr/local/lib/X11/${NEWTHEME}/start-button.png ]; then #chosen theme has menu icon.
+		if [ -f ${SYSROOT}/usr/local/lib/X11/pixmaps/start-button.png ];then #precaution.
+			if [ ! "`grep -F 'start-button.png' ${SYSROOT}/root/.jwmrc-tray`" ]; then
+				#the default is to use 'mini-dog.xpm' with text "Menu"...
+				sed -i 's%label="Menu" icon="puppy.svg"%icon="start-button.png"%' ${SYSROOT}$HOME/.jwmrc-tray
+			fi
+		else
+			#chosen theme does not have start-button.png, so go back to the mini-dog.xpm...
+			sed -i 's%icon="start-button.png"%label="Menu" icon="puppy.svg"%' ${SYSROOT}$HOME/.jwmrc-tray
+		fi
+	fi
 
- ONENAME="`basename $ONEDIR`"
- [ -f $ONEDIR/folder.svg ] && rsvg-convert -w 48 -h 48 -o /tmp/icon-switcher-proc/pis-${ONENAME}-folder.png $ONEDIR/folder.svg
- [ -f $ONEDIR/folder48.png ] && cp -f $ONEDIR/folder48.png /tmp/icon-switcher-proc/pis-${ONENAME}-folder.png
- [ -f $ONEDIR/www.svg ] && rsvg-convert -w 48 -h 48 -o /tmp/icon-switcher-proc/pis-${ONENAME}-www.png $ONEDIR/www.svg
- [ -f $ONEDIR/www48.png ] && cp -f $ONEDIR/www48.png /tmp/icon-switcher-proc/pis-${ONENAME}-www.png
- [ -f $ONEDIR/word.svg ] && rsvg-convert -w 48 -h 48 -o /tmp/icon-switcher-proc/pis-${ONENAME}-word.png $ONEDIR/word.svg
- [ -f $ONEDIR/word48.png ] && cp -f $ONEDIR/word48.png /tmp/icon-switcher-proc/pis-${ONENAME}-word.png
- [ -f $ONEDIR/spread.svg ] && rsvg-convert -w 48 -h 48 -o /tmp/icon-switcher-proc/pis-${ONENAME}-spread.png $ONEDIR/spread.svg
- [ -f $ONEDIR/spread48.png ] && cp -f $ONEDIR/spread48.png /tmp/icon-switcher-proc/pis-${ONENAME}-spread.png
- ICONSETSGUI=$ICONSETSGUI'
- <hbox space-expand="true" space-fill="false">
-     <pixmap space-expand="false" space-fill="false"><input file>/tmp/icon-switcher-proc/pis-'${ONENAME}'-folder.png</input></pixmap>
-     <pixmap space-expand="false" space-fill="false"><input file>/tmp/icon-switcher-proc/pis-'${ONENAME}'-www.png</input></pixmap>
-     <pixmap space-expand="false" space-fill="false"><input file>/tmp/icon-switcher-proc/pis-'${ONENAME}'-word.png</input></pixmap>
-     <pixmap space-expand="false" space-fill="false"><input file>/tmp/icon-switcher-proc/pis-'${ONENAME}'-spread.png</input></pixmap>
-     <text width-request="20" space-expand="true" space-fill="false"><label>""</label></text>
-     <vbox space-fill="true">
-     <text height-request="1" space-expand="true" space-fill="true"><label>""</label></text>
-     <button space-expand="false" space-fill="false"><label>'${ONENAME}'</label></button>
-     <text height-request="10" space-expand="false" space-fill="false"><label>""</label></text>
-     </vbox>
- </hbox><hseparator></hseparator>'
+	echo -n "$NEWTHEME" > ${SYSROOT}/etc/desktop_icon_theme
 
+	if [ "${SYSROOT}" ] ; then
+		echo
+		return
+	fi
+
+	#record current theme...
+	[ -z $ROX_DESKTOP ] && pidof ROX-Filer &>/dev/null && export ROX_DESKTOP=yes
+	if [ "$UPDATE" = "true" ]; then
+		#restart rox and jwm immediately...
+		roxfiler -p $HOME/Choices/ROX-Filer/PuppyPin
+		jwm -restart
+		kill $XPID
+	fi
+}
+export -f func_switch
+
+#parameters
+while [ $# != 0 ]; do
+	I=1
+	while [ $I -le `echo $# | wc -c` ]; do 
+		case $1 in
+			-sysroot) SYSROOT="$2" ; shift;;
+			-a) NEWTHEME="$2"; shift;;
+			-u) UPDATE=true;;
+			-h|--help)
+				echo '
+Usage: icon_switcher [OPTION]
+
+Options
+  -a THEME    Activate theme
+  -h          Show this help message
+  -u          Update desktop
+  -sysroot R  Set system root (use with -a THEME)'
+				exit;;
+		esac
+		shift
+		I=$[$I+1]
+	done
 done
 
-if [ "$GUI" = "yes" ];then
- export ICONSWITCHGUI='
- <window title="'$(gettext 'Puppy Icon Switcher')'" icon-name="gtk-convert" height-request="400" width-request="500" resizable="false">
- <vbox>
-   <vbox>
-   '"`/usr/lib/gtkdialog/xml_info fixed "desktop_icons.svg" 60 "$(gettext 'The Puppy icon switcher sets icons for both the <b>desktop</b> and the <b>menu</b>')"`"' 
-   </vbox>
-   <vbox space-expand="true" space-fill="true">
-     <vbox scrollable="true">
-       <eventbox name="bg" above-child="false" visible-window="true" space-expand="true" space-fill="true">
-         <vbox border-width="20" space-expand="false" space-fill="false">
-           '${ICONSETSGUI}'
-         </vbox>
-       </eventbox>
-     </vbox>
-   </vbox>
-   <hbox space-expand="false" space-fill="false"> 
-     <button>
-       '"`/usr/lib/gtkdialog/xml_button-icon cancel`"'
-       <label>'$(gettext 'Cancel')'</label>
-     </button>
-   </hbox>
- </vbox>
- </window>'
- 
- #set background pic
- BG_FILE="`cat $HOME/.config/wallpaper/bg_img`"
- [ ! "$BG_FILE" ] && BG_FILE="`grep -F '<backdrop' $HOME/.config/rox.sourceforge.net/ROX-Filer/pb_default | cut -d'>' -f2 | cut -d'<' -f1`"
- [ ! "$BG_FILE" ] && BG_FILE="`cat $HOME/Choices/ROX-Filer/PuppyPin | grep '<backdrop ' | cut -f 2 -d '>' | cut -f 1 -d '<'`"
- BG_PATH="`dirname "$BG_FILE"`"
- BG_NAME="`basename "$BG_FILE"`"
- echo '
- pixmap_path "'$BG_PATH'"
- style "bg" { bg_pixmap[NORMAL] = "'$BG_NAME'" }
- widget "*bg*" style "bg"' > /tmp/icon-switcher-proc/gtkrc_bg
- export GTK2_RC_FILES=/tmp/icon-switcher-proc/gtkrc_bg:/root/.gtkrc-2.0
+if [ "$NEWTHEME" ]; then
+	func_switch "$NEWTHEME"
+else
+	GUI=true
+	UPDATE=true
+	ICONSETSGUI=""
+	for ONEDIR in `find /usr/local/lib/X11/themes/ -mindepth 1 -maxdepth 1 -type d | tr '\n' ' '`; do
+		ONENAME="`basename $ONEDIR`"
+		[ -f $ONEDIR/folder.svg ] && rsvg-convert -w 48 -h 48 -o /tmp/pis-${ONENAME}-folder.png $ONEDIR/folder.svg
+		[ -f $ONEDIR/folder48.png ] && cp -f $ONEDIR/folder48.png /tmp/pis-${ONENAME}-folder.png
+		[ -f $ONEDIR/www.svg ] && rsvg-convert -w 48 -h 48 -o /tmp/pis-${ONENAME}-www.png $ONEDIR/www.svg
+		[ -f $ONEDIR/www48.png ] && cp -f $ONEDIR/www48.png /tmp/pis-${ONENAME}-www.png
+		[ -f $ONEDIR/word.svg ] && rsvg-convert -w 48 -h 48 -o /tmp/pis-${ONENAME}-word.png $ONEDIR/word.svg
+		[ -f $ONEDIR/word48.png ] && cp -f $ONEDIR/word48.png /tmp/pis-${ONENAME}-word.png
+		[ -f $ONEDIR/spread.svg ] && rsvg-convert -w 48 -h 48 -o /tmp/pis-${ONENAME}-spread.png $ONEDIR/spread.svg
+		[ -f $ONEDIR/spread48.png ] && cp -f $ONEDIR/spread48.png /tmp/pis-${ONENAME}-spread.png
+		ICONSETSGUI=$ICONSETSGUI'
+		<hbox space-expand="true" space-fill="true">
+		  <hbox border-width="8" spacing="20" space-expand="false" space-fill="false">
+		    <pixmap space-expand="false" space-fill="false"><input file>/tmp/pis-'${ONENAME}'-folder.png</input></pixmap>
+		    <pixmap space-expand="false" space-fill="false"><input file>/tmp/pis-'${ONENAME}'-www.png</input></pixmap>
+		    <pixmap space-expand="false" space-fill="false"><input file>/tmp/pis-'${ONENAME}'-word.png</input></pixmap>
+		    <pixmap space-expand="false" space-fill="false"><input file>/tmp/pis-'${ONENAME}'-spread.png</input></pixmap>
+		  </hbox>
+		  <text width-request="20" space-expand="false" space-fill="false"><label>""</label></text>
+		  <vbox space-expand="true" space-fill="true">
+		    <text height-request="1" space-expand="true" space-fill="true"><label>""</label></text>
+		    <button space-expand="false" space-fill="false">
+		      <label>'${ONENAME}'</label>
+		      <action>export UPDATE=true; func_switch "'${ONENAME}'"</action>
+		    </button>
+		    <text height-request="10" space-expand="false" space-fill="false"><label>""</label></text>
+		  </vbox>
+		</hbox>'
+	done
 
- . /usr/lib/gtkdialog/xml_info gtk #build bg_pixmap for gtk-theme
- RETSTUFF="`gtkdialog -p ICONSWITCHGUI`"
- eval "$RETSTUFF"
- NEWTHEME="$EXIT"
-fi #end gui
+	S='
+	<window title="'$(gettext 'Puppy Icon Switcher')'" icon-name="gtk-convert" height-request="500" width-request="520">
+	<vbox>
+	  '"`/usr/lib/gtkdialog/xml_info fixed "desktop_icons.svg" 60 "$(gettext 'The Puppy icon switcher sets icons for both the <b>desktop</b> and the <b>menu</b>')"`"' 
+	  <vbox space-expand="true" space-fill="true">
+	    <vbox scrollable="true">
+	      <eventbox name="bg" above-child="false" visible-window="true" space-expand="true" space-fill="true">
+	        <vbox border-width="20" space-expand="false" space-fill="false">
+	          '${ICONSETSGUI}'
+	        </vbox>
+	      </eventbox>
+	    </vbox>
+	  </vbox>
+	  <hbox space-expand="false" space-fill="false"> 
+	    <button space-expand="false" space-fill="false">
+	      '"`/usr/lib/gtkdialog/xml_button-icon internet.svg`"'
+	      <label>'$(gettext 'More themes')'</label>
+	      <action>defaulthtmlviewer http://www.murga-linux.com/puppy/viewtopic.php?t=31059 &</action>
+	    </button>'
+	    [ "`which ptheme`" ] && S=$S'<button space-expand="false" space-fill="false">
+	      '"`/usr/lib/gtkdialog/xml_button-icon puppy_theme.svg`"'
+	      <label>" '$(gettext 'Global theming')' "</label>
+	      <action>/usr/sbin/ptheme</action>
+	    </button>'
+	    S=$S'<text space-expand="true" space-fill="true"><label>""</label></text>
+	    <button>
+	      '"`/usr/lib/gtkdialog/xml_button-icon quit`"'
+	      <label>'$(gettext 'Quit')'</label>
+	    </button>
+	    '"`/usr/lib/gtkdialog/xml_scalegrip`"'
+	  </hbox>
+	</vbox>
+	</window>'
+	export ICONSWITCHGUI="$S"
+	
+	#set background pic
+	BG_FILE="`cat $HOME/.config/wallpaper/bg_img`"
+	[ ! "$BG_FILE" ] && BG_FILE="`cat $HOME/Choices/ROX-Filer/PuppyPin | grep '<backdrop ' | cut -f 2 -d '>' | cut -f 1 -d '<'`"
+	BG_PATH="`dirname "$BG_FILE"`"
+	BG_NAME="`basename "$BG_FILE"`"
+	echo '
+	pixmap_path "'$BG_PATH'"
+	style "bg" { bg_pixmap[NORMAL] = "'$BG_NAME'" }
+	widget "*bg*" style "bg"' > /tmp/gtkrc_bg
+	export GTK2_RC_FILES=/tmp/gtkrc_bg:/root/.gtkrc-2.0
 
-[ "$NEWTHEME" = "" ] && exit
-[ ! -d /usr/local/lib/X11/themes/${NEWTHEME} ] && exit
-
-if [ "$NEWTHEME" != "" ];then
- for ONESVG in `find /usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -name \*.svg | tr '\n' ' '`
- do
-  ONEBASENAME="`basename $ONESVG .svg`"
-  rm -f /usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png
-  rsvg-convert -w 48 -h 48 -o /usr/local/lib/X11/pixmaps/${ONEBASENAME}48.png $ONESVG
-  rm -f /usr/local/lib/X11/pixmaps/${ONEBASENAME}24.png
-  #rsvg-convert -w 24 -h 24 -o /tmp/icon-switcher-proc/${ONEBASENAME}24.png $ONESVG
-  ##if svg has transparency, JWM does not render properly in x16 bit color, screen out...
-  #pngtopnm -mix /tmp/icon-switcher-proc/${ONEBASENAME}24.png | pnmtopng > /usr/local/lib/X11/pixmaps/${ONEBASENAME}24.png
-  rsvg-convert -w 24 -h 24 -o /usr/local/lib/X11/pixmaps/${ONEBASENAME}24.png $ONESVG
- done
- for ONEPNG in `find /usr/local/lib/X11/themes/${NEWTHEME}/ -maxdepth 1 -type f -name \*.png | tr '\n' ' '`
- do
-  ONEBASENAME="`basename $ONEPNG .png`"
-  cp -f $ONEPNG /usr/local/lib/X11/pixmaps/
-  touch -m /usr/local/lib/X11/pixmaps/${ONEBASENAME}.png #v3.98
-  xONEBASENAME="`basename $ONEBASENAME 48`"
-  if [ "$xONEBASENAME" != "$ONEBASENAME" ];then #scale to 24 pixels...
-   pngtopnm -alpha $ONEPNG > /tmp/icon-switcher-proc/temp.pbm #separate transparency channel.
-   pnmscale -reduce 2 /tmp/icon-switcher-proc/temp.pbm > /tmp/icon-switcher-proc/temp2.pbm
-   pngtopnm $ONEPNG | pnmscale -reduce 2 | pnmtopng -alpha=/tmp/icon-switcher-proc/temp2.pbm > /usr/local/lib/X11/pixmaps/${xONEBASENAME}24.png
-   touch -m /usr/local/lib/X11/pixmaps/${xONEBASENAME}24.png #v3.98
-  fi
- done
- 
-  #110721 new standardised icons to show when mounted...
- if [ "`which pngoverlay`" -a -e /usr/local/lib/X11/pixmaps/closebox_outline48.png ];then #overlay app created by vovchik (see source /usr/sbin/pngoverlay.bac)
-  rm -f /usr/local/lib/X11/pixmaps/*_mntd*.png
-  cd /usr/local/lib/X11/pixmaps
-  cp -f /usr/sbin/pngoverlay /usr/local/lib/X11/pixmaps/ #dumb, but needs to be in same folder.
-  for ONEDRV in card drive floppy optical usbdrv
-  do
-   ./pngoverlay ${ONEDRV}48.png closebox_outline48.png ${ONEDRV}_mntd48.png #background foreground output.
-   ./pngoverlay ${ONEDRV}48.png locked_outline48.png ${ONEDRV}_mntd_boot48.png
-  done
-  rm -f /usr/local/lib/X11/pixmaps/pngoverlay
- fi
- 
- #110912 modify jwm to use menu icon 'start-button.png' if present...
- #note, similar code also in 3builddistro in Woof.
- if [ -f /root/.jwmrc-tray ];then
-  if [ -f /usr/local/lib/X11/${NEWTHEME}/start-button.png ];then #chosen theme has menu icon.
-   if [ -f /usr/local/lib/X11/pixmaps/start-button.png ];then #precaution.
-    if [ "`grep 'start-button\.png' /root/.jwmrc-tray`" = "" ];then
-     #the default is to use 'mini-dog.xpm' with text "Menu"...
-     PTN1='s%label="Menu" icon="mini-dog\.xpm"%icon="start-button.png"%'
-     sed -i -e "$PTN1" /root/.jwmrc-tray
-    fi
-   else
-    #chosen theme does not have start-button.png, so go back to the mini-dog.xpm...
-    PTN2='s%icon="start-button\.png"%label="Menu" icon="mini-dog.xpm"%'
-    sed -i -e "$PTN2" /root/.jwmrc-tray
-   fi
-  fi
- fi
- if [ "$GUI" = "yes" ];then
-   #v4.00 HairyWill restart rox and jwm immediately...
-   /usr/lib/gtkdialog/box_ok "$(gettext 'Puppy Icon Switcher')" complete "`eval_gettext \"You have chosen the <b>\\\${NEWTHEME}</b> theme. These are icons for the desktop and top-level of menu. Click OK button and you will see them...\"`"
-
-   #w477 record current theme...
-   echo -n "$NEWTHEME" > /etc/desktop_icon_theme
-
-   rox -p=/root/Choices/ROX-Filer/PuppyPin
-   fixmenus #100411
-   jwm -restart
-   
-   [ `pidof xfce4-session` ] && xfdesktop --reload
-   
- fi
+	. /usr/lib/gtkdialog/xml_info gtk #build bg_pixmap for gtk-theme
+	gtkdialog -p ICONSWITCHGUI
 fi
-
-
-###END###
